### ISSUE TITLE
[INIT] - 초기 프로젝트 세팅

### ISSUE THREAD

**Issue by bbabbi** [2024-2-3M1S/AutoRepo-Server#1]
## ✨ 어떤 기능인가요?

> 개발에 들어가기 전 기본적인 세팅을 진행합니다.

## ✅ 작업 상세 내용

- [x] 이슈, PR 템플릿 설정
- [x] 스프링부트 프로젝트 세팅
- [x] Swagger 세팅
- [x] Exception/Error/Success 세팅
- [x] Docker CI/CD

**Comment by seochan99** [comment]
이슈, PR 템플릿 설정은 Client랑 같은걸로 해서 Main에 바로. 올려둘께용

**Comment by bbabbi** [comment]
> 이슈, PR 템플릿 설정은 Client랑 같은걸로 해서 Main에 바로. 올려둘께용

넵~! 감사합니당
